# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 773e99f98e8e16fd3eb50d1b38442c86b60aa77e916bb6c87e8b1e37cd68353b34371c1425a55c973aade160b0a5c5fd1fef1623f24bffc25ddf59340d75d063

test:
  secret_key_base: ab63b30a24c1543790ee47808fd8664bfe2d0a098b661229ce2fad72b80cfe9436ea57c07cc29a80eb66c750261ed20dc423813fd2a126ea491e268cb68ed5e4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
